version: '3.9'
services:

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - ./influxdb2:/var/lib/influxdb2:rw
    ports:
      - '8086:8086'
    networks:
      - influxdbnet
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=telegraf
      - DOCKER_INFLUXDB_INIT_PASSWORD=telegraf
      - DOCKER_INFLUXDB_INIT_ORG=telegraf_org
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf_bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    restart: unless-stopped

  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - influxdbnet
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=telegraf_org
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    restart: unless-stopped
    depends_on:
      - influxdb

networks:
  influxdbnet:
    driver: bridge
